name: build

on:
  workflow_dispatch:
    inputs:
      dryRun:
        description: 'Dry Run (set to "true" for a dry run)'
        required: false
        default: 'false'
  push:
    branches: [main, release-*]
  pull_request:
    branches: [main, release-*]

jobs:
  build:
    # runs-on: [self-hosted, linux-amd64]
    # env:
    #   # The var will be a string of `true` or `false`
    #   IS_RELEASE_BRANCH: ${{ startsWith(github.ref, 'refs/heads/release') || github.ref == 'refs/heads/main' }}

    steps:
      - name: Checkout Repo With Tag History
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: shellcheck
        uses: reviewdog/action-shellcheck@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          path: "src/content"
          pattern: "*.sh"
